# -*- coding: utf-8 -*-

dh.define_table('acontent',
                    Field('ref_article', dh.article,
                                        length=None,
                                        #default=None,
                                        required=True,
                                        requires=IS_NOT_EMPTY(),
                                        notnull=True,
                                        unique=False,
                                        label='Article',
                                        #comment=None,
                                        writable=True,
                                        readable=True,
                                        update=None),
                    Field('content_type', type='string',
                                        length=16,
                                        default='para',
                                        required=False,
                                        requires=[IS_NOT_EMPTY(),
                                                    IS_IN_SET('para',
                                                                'code',
                                                                'object',
                                                                'attachment')],
                                        notnull=True,
                                        unique=False,
                                        label='Content Type',
                                        #comment=None,
                                        writable=True,
                                        readable=True,
                                        update=None),
                    Field('ref_content', type='integer',
                                        length=None,
                                        default=None,
                                        required=True,
                                        requires=IS_NOT_EMPTY(),
                                        notnull=True,
                                        unique=False,
                                        label='Content',
                                        #comment=None,
                                        writable=False,
                                        readable=False,
                                        update=None),
                    Field('sort_order', type='integer',
                                        length=None,
                                        default=1,
                                        required=True,
                                        requires=IS_INT_IN_RANGE(0, 60),
                                        notnull=True,
                                        unique=False,
                                        label='Sort Order',
                                        #comment=None,
                                        writable=True,
                                        readable=True,
                                        update=None),
                    Field('cdate', type='datetime',
                                        length=None,
                                        #default=datetime.utcnow(),
                                        required=True,
                                        requires=IS_NOT_EMPTY(),
                                        notnull=True,
                                        unique=False,
                                        label='Create Date',
                                        #comment=None,
                                        writable=False,
                                        readable=True,
                                        update=None),
                    Field('mdate', type='datetime',
                                        length=None,
                                        #default=datetime.utcnow(),
                                        required=True,
                                        requires=IS_NOT_EMPTY(),
                                        notnull=True,
                                        unique=False,
                                        label='Last Modified',
                                        #comment=None,
                                        writable=False,
                                        readable=False,
                                        #update=datetime.utcnow()),
                                        ),
                    Field('is_deleted', type='boolean',
                                        length=None,
                                        default=False,
                                        required=False,
                                        #requires=IS_NOT_EMPTY(),
                                        notnull=False,
                                        unique=False,
                                        #label='Deleted',
                                        #comment=None,
                                        writable=False,
                                        readable=False,
                                        update=None),
                    migrate=True)



