# -*- coding: utf-8 -*-

dh.define_table('content_object',
                    Field('object_type', type='string',
                                        length=16,
                                        default=None,
                                        required=True,
                                        requires=[IS_NOT_EMPTY(),
                                                    IS_IN_SET('URL',
                                                                'Image',
                                                                'Video',
                                                                'YouTube')],
                                        notnull=True,
                                        unique=False,
                                        label='Object Type',
                                        #comment=None,
                                        writable=True,
                                        readable=True,
                                        update=None),
                    Field('stored_reference', type='string',
                                        length=2000,
                                        default=None,
                                        required=True,
                                        requires=IS_NOT_EMPTY(),
                                        notnull=True,
                                        unique=False,
                                        label='Path',
                                        comment='Could be absolute path for URL, YouTube and relative for Image, Video.',
                                        writable=True,
                                        readable=True,
                                        update=None),
                    Field('caption', type='string',
                                        length=256,
                                        default=None,
                                        required=False,
                                        #requires=IS_NOT_EMPTY(),
                                        notnull=False,
                                        unique=False,
                                        label='Caption',
                                        #comment=None,
                                        writable=True,
                                        readable=True,
                                        update=None),
                    migrate=True)



