# -*- coding: utf-8 -*-

dh.define_table('content_attachment',
                    Field('attachment_mime', type='string',
                                        length=16,
                                        default=None,
                                        required=True,
                                        requires=[IS_NOT_EMPTY(),
                                                    IS_IN_SET('application/json',
                                                                'application/pdf',
                                                                'application/zip',
                                                                'application/msword',
                                                                'application/vnd.ms-excel',
                                                                'text/plain',
                                                                'text/csv',
                                                                'text/xml',
                                                                'image/jpeg',
                                                                'image/png',
                                                                'video/mp4',
                                                                'audio/aac')],
                                        notnull=True,
                                        unique=False,
                                        label='Attachment Type',
                                        #comment=None,
                                        writable=True,
                                        readable=True,
                                        update=None),
                    Field('stored_reference', type='string',
                                        length=2000,
                                        default=None,
                                        required=True,
                                        requires=IS_NOT_EMPTY(),
                                        notnull=True,
                                        unique=False,
                                        label='Path',
                                        #comment=None,
                                        writable=True,
                                        readable=True,
                                        update=None),
                    Field('title', type='string',
                                        length=256,
                                        default=None,
                                        required=True,
                                        requires=IS_NOT_EMPTY(),
                                        notnull=True,
                                        unique=False,
                                        label='Title',
                                        #comment=None,
                                        readable=True,
                                        writable=True,
                                        update=None),
                    migrate=True)



